### ISSUE TITLE
Successfully installed the SDK and authenticated with DDL servers, but unable to run scripts due to weird error

### ISSUE THREAD

**Issue by ManicQuinn** [cyb3rdog/vector-python-sdk#10]
Feb 11 06:42:13 escapepod start.sh[8336]: (Bot 1, Vosk) Processing...
Feb 11 06:42:17 escapepod start.sh[8336]: (Bot 1) End of speech detected.
Feb 11 06:42:18 escapepod start.sh[8336]: Bot 1 Transcribed text: best
Feb 11 06:42:18 escapepod start.sh[8336]: Custom Intent Matched: test - test - intent_greeting_hello
Feb 11 06:42:18 escapepod start.sh[8336]: Executing: /bin/python3 /home/pi/vector-python-sdk/examples/tutorials/01_hello_world.py
Feb 11 06:42:18 escapepod start.sh[8336]: exit status 1: Traceback (most recent call last):
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/home/pi/vector-python-sdk/examples/tutorials/01_hello_world.py", line 22, in <module>
Feb 11 06:42:18 escapepod start.sh[8336]:     import anki_vector
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/usr/local/lib/python3.9/dist-packages/anki_vector/__init__.py", line 22, in <module>
Feb 11 06:42:18 escapepod start.sh[8336]:     from . import messaging
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/__init__.py", line 42, in <module>
Feb 11 06:42:18 escapepod start.sh[8336]:     from . import protocol
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/protocol.py", line 24, in <module>
Feb 11 06:42:18 escapepod start.sh[8336]:     from .behavior_pb2 import *
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/behavior_pb2.py", line 16, in <module>
Feb 11 06:42:18 escapepod start.sh[8336]:     from anki_vector.messaging import messages_pb2 as anki__vector_dot_messaging_dot_messages__pb2
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/messages_pb2.py", line 17, in <module>
Feb 11 06:42:18 escapepod start.sh[8336]:     from anki_vector.messaging import response_status_pb2 as anki__vector_dot_messaging_dot_response__status__pb2
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/usr/local/lib/python3.9/dist-packages/anki_vector/messaging/response_status_pb2.py", line 33, in <module>
Feb 11 06:42:18 escapepod start.sh[8336]:     _descriptor.EnumValueDescriptor(
Feb 11 06:42:18 escapepod start.sh[8336]:   File "/usr/local/lib/python3.9/dist-packages/google/protobuf/descriptor.py", line 755, in __new__
Feb 11 06:42:18 escapepod start.sh[8336]:     _message.Message._CheckCalledFromGeneratedFile()
Feb 11 06:42:18 escapepod start.sh[8336]: TypeError: Descriptors cannot not be created directly.
Feb 11 06:42:18 escapepod start.sh[8336]: If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
Feb 11 06:42:18 escapepod start.sh[8336]: If you cannot immediately regenerate your protos, some other possible workarounds are:
Feb 11 06:42:18 escapepod start.sh[8336]:  1. Downgrade the protobuf package to 3.20.x or lower.
Feb 11 06:42:18 escapepod start.sh[8336]:  2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
Feb 11 06:42:18 escapepod start.sh[8336]: More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
Feb 11 06:42:18 escapepod start.sh[8336]: Custom Intent Exec Output:
Feb 11 06:42:18 escapepod start.sh[8336]: Bot 1 Intent Sent: intent_greeting_hello
Feb 11 06:42:18 escapepod start.sh[8336]: No Parameters Sent
Feb 11 06:42:18 escapepod start.sh[8336]: This is a custom intent or plugin!
Feb 11 06:42:18 escapepod start.sh[8336]: Bot 1 request served.

**Comment by ManicQuinn** [comment]
Update 1, running the script outside of wire-pod makes it run normally, which means the issue is on wire-pod and not the sdk, I'll close it here with the output:
```
 python3 /home/pi/vector-python-sdk/examples/tutorials/01_hello_world.py
23:58:12.952               robot.Robot WARNING  No serial number or name provided. Automatically selecting                                                                                                                                 REDACTED
23:58:12.965     connection.Connection    INFO  Connecting to REDACTED:443 for Vector-REDACTED using /home/pi                                                                                                                                 /.anki_vector/Vector-REDACTED.cert
23:58:19.725     connection.Connection    INFO  BehaviorControl control_granted_response { }
Say 'Hello World'...
```

**Comment by ba2512005** [comment]
run "pip install protobuf==3.20.3" 
Then it should work
