### ISSUE TITLE
Get connectionrefusederror Errno 61

### ISSUE THREAD

**Issue by pocketmax** [cyb3rdog/vector-python-sdk#4]
![image](https://user-images.githubusercontent.com/206058/120064481-36c0f080-c021-11eb-9ff2-4ad32e6bccdb.png)
I get this error when I run this command...
`python3 -m anki_vector.configure_pod`

I'm using Python 3.9.0 on a mac

**Comment by fredericowu** [comment]
get your robot IP and try that:

python3 -m anki_vector.configure_pod -i <VECTOR_IP>

**Comment by pocketmax** [comment]
![image](https://user-images.githubusercontent.com/206058/120100701-e3b96d00-c0f6-11eb-919f-9ae7d329a4f6.png)
I tried that. And I also tried passing in the other arguments in the CLI.

I can also ping the ip address from my workstation as well
![image](https://user-images.githubusercontent.com/206058/120100730-20856400-c0f7-11eb-9e86-baa2a81d5c04.png)

**Comment by fredericowu** [comment]
Try:
telnet VectorIp 443

And tell me if connects.
Looks like for some reason it is not taking connections.
Try also to restart the vector.
If anything work, I would suggest you to download the latest image and follow the OTA deployment instructions.

**Comment by pocketmax** [comment]
omg, I'm such a dummy! I've been trying this in dev mode (holding down the button on his back until the blue bars show) and of course port 443 would be closed! Thanks for all your help. I really appreciate it!
