### ISSUE TITLE
Fail to authenticate request issue

### ISSUE THREAD

**Issue by soominimini** [cyb3rdog/vector-python-sdk#6]
Hi i am doing vector project based on your library and code!
Now I am done with the whole escape pod process and i am running python code which you provide.
But problem is that i keep receiving error code.

Fail to authenticate request
![1627637328656](https://user-images.githubusercontent.com/28712478/127634547-579a71ad-5cde-4f4f-8e80-20aecfd72260.png)

Can you tell me what i did wrong?

Honestly it was working well yesterday but since after i reboot my computer, it stops working

**Comment by fredericowu** [comment]
Hey, did you figure out?
Looks like you didn’t setup the ask properly

**Comment by soominimini** [comment]
> Hey, did you figure out? Looks like you didn’t setup the ask properly
> […](#)
> Sent from my iPhone
> On Jul 30, 2021, at 3:41 AM, soomin shin ***@***.***> wrote: ﻿ Hi i am doing vector project based on your library and code! Now I am done with the whole escape pod process and i am running python code which you provide. But problem is that i keep receiving error code. Fail to authenticate request Can you tell me what i did wrong? Honestly it was working well yesterday but since after i reboot my computer, it stops working — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by soominimini** [comment]
I fixed this issue, well honestly i didn't fix, suddenly the issue had been fixed
but as i heard, there was a problem in escaped pod server..?
